services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles # Your TZ Here
      - URL=example.duckdns.org # Your Domain Here
      - VALIDATION=duckdns
      - CERTPROVIDER=zerossl
      - EMAIL=email@example.com # Your Email Here
    env_file:
      - path: .env.example # Must contain DUCKDNSTOKEN env var if using duckdns
        required: true
    volumes:
      - ssl:/config/etc/letsencrypt/
  ftp:
    image: shawn636/mini-ftp:latest
    container_name: ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - FTP_USER=your-username
      - FTP_PASS=your-password
      - ADDRESS=example.duckdns.org
      - TLS_CERT=/ssl/live/example.duckdns.org/fullchain.pem # Replace domain with your own
      - TLS_KEY=/ssl/live/example.duckdns.org/privkey.pem # Replace domain with your own
    volumes:
      - /path/to/ftp-data:/ftp
      - /path/to/ssl:/ssl
